import { style } from '@angular/animations';
export class AppConfig {
    public static BASE_URL =                      'api';
    public static INTEREST_SPRITES =              '/public/interest_images/interest_sprite.webp';//to get the interest sprite image.
    public static CSS_SPRITES =                   '/public/header_icons/header_sprite.svg';           //to get the header icon image.
    public static LOGO_PATH =                     './../../assets/icons/Olcademy.png';
    public static REGISTER_USER =                 AppConfig.BASE_URL + '/register';
    public static LOGIN =                         AppConfig.BASE_URL + '/login';
    public static PROFILE_IMG =                   AppConfig.BASE_URL + '/profileImage/';
    public static GET_SKILLS =                    AppConfig.BASE_URL + '/skills/';
    public static GET_RESEARCH =                  AppConfig.BASE_URL + '/research/';
    public static GET_CERTIFICATE =               AppConfig.BASE_URL + '/certificate/';
    public static GET_SOCIAL =                    AppConfig.BASE_URL + '/social_profile/';
    public static GET_Experience =                 AppConfig.BASE_URL + '/experience/';///education
    public static GET_EDUCATIION =                 AppConfig.BASE_URL + '/education/';
    public static GET_USER_DATA =                 AppConfig.BASE_URL + '/userDetails/';

    public static CATEGORY_LIST_URL =             AppConfig.BASE_URL + '/categories';
    public static TEST_LIST_URL =                 AppConfig.BASE_URL + '/testcategories';
    public static LOGIN_DETAILS =                 AppConfig.BASE_URL + '/user/';                              //to get the token set by the backend along with the user details.
    public static USER_IMAGE =                    AppConfig.BASE_URL + '/userProfileImg/';                       //to get the user image path according to the php model.
    public static SHOW_POPUP_GET =                AppConfig.BASE_URL + '/user';                              //to get the boolean parameter weather to show the pop up or not.
    public static GET_SAVED_INTEREST =            AppConfig.BASE_URL + '/userInterest/';                  //to get the user saved interest.
    public static POST_INTERST_PATH =             AppConfig.BASE_URL + '/userInterest/';                   // to send the user selected interest.
    public static GET_BLOGS_URL =                 AppConfig.BASE_URL + '/blog';                               //to get all the blogs
    public static GET_SELECTED_CATEGORY_BLOGS =   AppConfig.BASE_URL + '/';                     //
    public static POST_INTEREST_MY_FEED =         AppConfig.BASE_URL + '/userinterest/';
    public static GET_PARTICULAR_POST =           AppConfig.BASE_URL + '/post/';
    public static GET_USER_BOOKMARKED =           AppConfig.BASE_URL + '/bookmarks';
    public static GET_USER_POST =                 AppConfig.BASE_URL + '/yourPost';
    public static IMAGES_UPLOADS =                AppConfig.BASE_URL + '/uploadImages';
    public static VIDEOS_UPLOADS =                AppConfig.BASE_URL + '/uploadVideos';
    public static DOCUMENT_UPLOADS =              AppConfig.BASE_URL + '/uploadDocuments';
    public static PUBLISH_POST =                  AppConfig.BASE_URL + '/post';
    public static DELETE_POST =                   AppConfig.BASE_URL + '/post/'
    public static UPDATE_POST =                   AppConfig.BASE_URL + '/post/';
    public static INCREASE_LIKES =                AppConfig.BASE_URL + '/like/';
    public static DELETE_LIKES =                  AppConfig.BASE_URL + '/like';
    public static INCREASE_BOOKMARK =             AppConfig.BASE_URL + '/bookmarks/';
    public static GET_COMMENT =                   AppConfig.BASE_URL + '/comments/';
    public static POST_COMMENT =                  AppConfig.BASE_URL + '/comment/';
    public static POST_REPORT =                   AppConfig.BASE_URL + '/report/post';
    public static POST_COMMENT_LIKE =             AppConfig.BASE_URL + '/likeComment/';
    public static GET_REPLY  =                    AppConfig.BASE_URL + '/comments/replies/';
    public static POST_REPLY  =                   AppConfig.BASE_URL + '/replyComment/';
    public static REPORT_REPLY =                  AppConfig.BASE_URL + '/report/reply_comment';
    public static REPORT_COMMENT =                AppConfig.BASE_URL + '/report/comment';
    public static GOOGLE_LOGIN =                  AppConfig.BASE_URL + '/auth/google';
    public static GET_CONNECTIONS =               AppConfig.BASE_URL + '/connection';
    public static PENDING_REQUEST =               AppConfig.BASE_URL + '/pending';
    public static SENT_REQUEST =                  AppConfig.BASE_URL + '/requested';
    public static SUGGESTIONS =                   AppConfig.BASE_URL + '/suggestion';
    public static FOLLOW_USER =                   AppConfig.BASE_URL + '/follow/';
    public static UNFOLLOW_USER =                 AppConfig.BASE_URL + '/unfollow/';
    public static ACCEPT_CONNECT_REQUEST =        AppConfig.BASE_URL + '/connect/accept';
    public static REJECT_CONNECTION_REQUEST =     AppConfig.BASE_URL + '/connect/cancel'
    public static REMOVE_CONNECTION =             AppConfig.BASE_URL + '/connect/disconnect';
    public static SEND_CONNECTION_REQUEST =       AppConfig.BASE_URL + '/connect/request';
    public static PUT_USER_DATA_F =               AppConfig.BASE_URL + '/userDetailsfirst/';
    public static PUT_USER_DATA_S =               AppConfig.BASE_URL + '/userDetailssecond/';
  }
